name: "Tags"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Target Tag"
        required: true

jobs:
  tags:
    name: "Tags"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@06ac3e56e828129c17054b39d11317584af1bd88 # v1.3.1
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.GH_PAT }}
